### ISSUE TITLE
HALF (FP16)

### ISSUE THREAD

**Issue by bhack** [CNugteren/Claduc#10]
From https://github.com/tiny-dnn/tiny-dnn/issues/355#issuecomment-255591703 I'm guessing if makes sense to introduce HALF at CLCudaAPI level. What do you think? /cc @edgarriba @randl

**Comment by Randl** [comment]
Agreed, FP16 make sense mostly with GPUs, i.e. as soon as we have working GPU we'd want to use FP16 on it.

http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__HALF.html#group__CUDA__MATH__INTRINSIC__HALF
https://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml/cl_khr_fp16.html

**Comment by CNugteren** [comment]
I understand the benefit of FP16. But what exactly are you requesting from CLCudaAPI? [CLBlast](https://github.com/CNugteren/CLBlast) already supports FP16 and is based on CLCudaAPI, so I'm not sure what exactly you would like to change.

**Comment by bhack** [comment]
For example we could handle half like float in https://github.com/CNugteren/CLCudaAPI/blob/master/samples/simple.cc#L106

**Comment by bhack** [comment]
If we don't put here we need to replicate something like https://github.com/CNugteren/CLTune/blob/master/include/internal/half.h in every application

**Comment by CNugteren** [comment]
Well that's the host-version of half-precision support (pure C++, no OpenCL), right? I am not sure this library is the right place to put that into.

You'll probably want much more than just `half FloatToHalf(const float value)` and `float HalfToFloat(const half value)` as provided in the `half.h` you mentioned, so then it's probably better to include something like http://half.sourceforge.net/? Of course, we could copy-paste that library here, but that doesn't feel like good either since it is unrelated to OpenCL or CUDA.

**Comment by bhack** [comment]
@Randl has prototyped this for us https://gist.github.com/Randl/169004c2377fef7db28a418cc72e330c

**Comment by bhack** [comment]
What type we use in https://github.com/CNugteren/CLCudaAPI/blob/master/samples/simple.cc#L112 with half?

**Comment by CNugteren** [comment]
The regular OpenCL `cl_half` should work fine (https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/cl_khr_fp16.html). Why wouldn't it?

**Comment by bhack** [comment]
So do you mean `CLCudaAPI::Buffer<cl_half>` and maintain our own custom half type on  host?

**Comment by CNugteren** [comment]
Yes, I guess that could be an option. Or you use the `half` data-type from the library I mentioned or from @Randl's prototype you mentioned above. In any case all that matters for the OpenCL kernel is the size of the data-type (16-bits).

But if you have strong reasons why something like this should be part of CLCudaAPI, do let me know. I can of course add @Randl's prototype in combination with half-to-float and float-to-half conversions (although that wouldn't be portable because it requires SSE - it won't work on ARM NEON for example). But to me it seems a bit out-of-place here, since it has no relation to OpenCL.

**Comment by bhack** [comment]
Probably we can let to user of this headers (CLCudaAPI) to reimplement this on host every time or probably somebody will add an common header host side. But at the end I hope that this WG14 proposal will pass soon: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2016.pdf
