### ISSUE TITLE
Save and load IR

### ISSUE THREAD

**Issue by bhack** [CNugteren/Claduc#6]
Can you add public methods for save and load IR in the Program class? Or only a constructor with the binary param instead of the source.

/cc @edgarriba

**Comment by CNugteren** [comment]
What exactly do you mean? Loading/saving from disk?

There is already saving the IR to string:

```
  // Retrieves a binary or an intermediate representation of the compiled program
  std::string GetIR() const {
```

and loading a binary from string:

```
  // Binary-based constructor with memory management
  explicit Program(const Device &device, const Context &context, const std::string& binary):
```

**Comment by bhack** [comment]
Yes. The save was just an option to write on file cause we already has a string (but nevermind). But for this binary loader I really missed to catch it cause I was following https://github.com/CNugteren/CLCudaAPI/blob/master/doc/api.md and seems that is not documented.

**Comment by CNugteren** [comment]
OK, that's a bug in the documentation then. I have fixed it in the development branch. However, this function is OpenCL only (for now?), so be aware.

I guess it is better to leave the disk I/O to the user of CLCudaAPI, do you agree?

**Comment by bhack** [comment]
Ok thanks. Yes disk I/O it is a design choice.

**Comment by bhack** [comment]
Can 
`Program(const Device &device, const Context &context, const std::string& binary)`
be supported in cuda using [cuModuleLoadData](http://llvm.org/docs/NVPTXUsage.html#executing-ptx)?

**Comment by CNugteren** [comment]
Actually, `cuModuleLoadDataEx` (a similar function) is already used when creating a kernel. There is a bit of a mismatch between the CUDA and OpenCL versions of a program, so that's why it's done like that. Nevertheless, I think I can change the CUDA version of the `Program` class to also accept the PTX string and then just pass it down to the kernel class.

I don't have a CUDA device to test on at this moment. I did implement something, but there could be errors in there. Could you test it for me? A patch is available here:
https://gist.github.com/CNugteren/a5b3996d23e88d2355578544fa32e843

**Comment by bhack** [comment]
Don't you like it cause there are two unused parameters?

**Comment by CNugteren** [comment]
I have access to a CUDA device again to test. I have now applied the above patch and also added a new unit-test to test loading and saving from/to IR or PTX. As far as the tests are concerned it now works with both CUDA and OpenCL.

Can you test it for me as well?

**Comment by bhack** [comment]
All tests passed.
